### ISSUE TITLE
Lazy load data in templates through iterable callback

### ISSUE THREAD

**Issue by mabar** [contributte/model#1]
Simplify

```latte
{var $_items => $items()}
{foreach $_items as $item}
{/foreach}
```

into

```latte
{foreach $items as $item}
{/foreach}
```

(Simplifies this case https://github.com/componette/componette/blob/b68f92f2c709f2a8502f0d6762d983a0c86842aa/app/modules/Front.Portal/Base/Controls/SideMenu/SideMenu.php#L30-L37)

**Comment by mabar** [comment]
@f3l1x Maybe we could add it to contributte/utils instead. Or contributte/latte if this will be used only for latte templates.

**Comment by f3l1x** [comment]
This is simple use-case, but the main idea is much much bigger.

**Comment by f3l1x** [comment]
```php

Contributte\Model\ViewModel\LazyCollection;

$collection = LazyCreator::fromCallback(function() {
 // return data..
})

// $collection instanceof LazyCollection;
// to see type
```

**Comment by mabar** [comment]
Closed by initial commit
